### ISSUE TITLE
Depends on Romkan, which fails on "pip install romkan"

### ISSUE THREAD

**Issue by voxlz** [jShiohaha/JapaneseVerbConjugator#6]

**Comment by voxlz** [comment]
`Collecting romkan
  Using cached romkan-0.2.1.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3a4uv583/romkan_71326df14aeb470896c8875c3777ac5d/setup.py", line 8, in <module>
          import os, json, imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.`

**Comment by Sandman-Ren** [comment]
Consulted with ChatGPT has led me to the following solution:

- `imp` was deprecated in Python 3.12, downgrade to an older version. I ended up using `3.10`
- the underlying romkan may have an encoding issue on Windows that defaults to `cp1252` encoding. Make sure you use UTF8 by setting

```
set PYTHONUTF8=1
pip install japaneseverbconjugator
```

Powershell:
```ps
$env:PYTHONUTF8=1
pip install japaneseverbconjugator
```

**Comment by Bel-Shazzar** [comment]
Hi, since this repo does not seem to be updated anymore I published my [fork](https://github.com/Bel-Shazzar/JapaneseVerbConjugator) on [PyPi](https://pypi.org/project/japanese-verb-conjugator-v2/)

This Issue is resolved there.
